rss:
  - name: techcrunch
    url: https://techcrunch.com/category/artificial-intelligence/feed/
  - name: mit
    url: https://www.technologyreview.com/feed/
  - name: ycombinator
    url: https://news.ycombinator.com/rss
  - name: venturebeat
    url: https://venturebeat.com/category/ai/feed/
  - name: verge
    url: https://www.theverge.com/rss/ai-artificial-intelligence/index.xml